version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "7860:7860"
    depends_on:
      - fastapi

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"