version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "7860:7860"
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - fastapi
    environment:
      - DATABASE_URL=sqlite:///data/new.db
      - API_URL=http://fastapi

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8000:80"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/new.db

volumes:
  sqlite_data: