# Use the official Python 3.11 image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code into the container
COPY . .

# Install the dependencies
RUN pip install -r requirements.txt

# Expose the port that Gradio will run on
EXPOSE 7860

# Command to run the Gradio app using uvicorn
CMD ["uvicorn", "src.web:app", "--host", "0.0.0.0", "--port", "7860"]
